Add optional setting to include tip in donation amount
kevinhughes27/shopify-tax-receipts pull request #220
Opened 2022-04-06 01:08 UTC by davidcol25

This feature will allow an organization to add the tip in the total donation amount. This feature is disabled by default and can be enabled in the charity settings.

2022-04-06 02:24 UTC, kevinhughes27 requested changes
Looks great! Nice stuff :smile_cat: 

I'd like to change the naming from `add_tip` to `include_tip` and in the user facing copy as well because I think that is a better way to express it to the user interface and in our code.

Another screenshot would be great here too. Just of the charity settings form.

I'd also like to see a new test added that uses an order fixture with a Tip (or modifies an existing fixture in a reasonable way) and the expected outcome

2022-04-06 02:26 UTC, kevinhughes27 commented on db/migrate/20220401184643_add_tip.rb
> +end
nitpick but this file is missing a final new line.

2022-04-06 02:40 UTC, kevinhughes27 commented on db/migrate/20220401184643_add_tip.rb
> +end
I recommend finding the setting to in your editor to do this automatically

2022-04-07 01:25 UTC, nosdf227 commented
![Settings](https://user-images.githubusercontent.com/34284618/162101491-61bcebda-ac1e-4eca-bb80-fc38ee396d4f.png)

This is the screenshot for the Settings tab. You can see that we added the checkbox at the bottom.

2022-04-07 01:34 UTC, nosdf227 commented
![Donations](https://user-images.githubusercontent.com/34284618/162102223-7c0e1ede-f56d-44cc-b942-62fd3147f37a.png)

Details for the `19.5` in the `Amount` column:
* Bought 2 items at $15 each (for a subtotal of $30)
* Percentage eligible for tax receipt : 50.0%
* Tip of $4.50

2022-04-07 01:48 UTC, davidcol25 commented
> I'd also like to see a new test added that uses an order fixture with a Tip (or modifies an existing fixture in a reasonable way) and the expected outcome

Could you maybe give us some guidance on how to create a new order fixture, can it be generated? Thank you.

2022-04-07 18:05 UTC, kevinhughes27 commented
The fixtures for these tests are just json files in [this directory](https://github.com/kevinhughes27/shopify-tax-receipts/blob/master/test/fixtures/order.json) that we load up and use in the test. This json blob is the same blob Shopify sends in the order webhook. You can also get the json for any order by adding `.json` to the url in your test shop admin. 

I'd recommend grabbing the json from the order you used for the screenshot above. You might need to edit the shop name to match the test shop which you can find in the other fixtures.

2022-04-09 16:50 UTC, kevinhughes27 approved these changes
test looks good to me. Thanks for adding.

I just realized that I had CI slightly mis-configured and it is not running tests for forked branches. I have fixed the setting so if you push a blank commit or amend the last commit to change it then tests will run and we can see CI pass before I merge.

as part of this I also realized that your last PR https://github.com/kevinhughes27/shopify-tax-receipts/pull/219 broke some tests because the default order in the test now needs to reach out to Shopify for more information in order to render the home page. This can be fixed by adding more data to the donation in the test to prevent the api call or by mocking the api call. Can I get you to either put up a new PR for that fix or fix it in this PR? I'd like to get CI green before merging.

If you can get those things done I'll be able to merge this week and get the feature live! We could also make an announcement to users of the app about this because it has been requested a few times.

2022-04-09 16:50 UTC, kevinhughes27 commented on test/fixtures/order_with_tip.json
> +}
another nit on a missing newline here

2022-04-13 18:18 UTC, kevinhughes27 approved these changes
I'll look into getting this deployed as soon as I can!

2022-04-13 21:25 UTC, davidcol25 commented
> I'll look into getting this deployed as soon as I can!

Alright, thank you so much!

2022-04-27 15:06 UTC, merged

2022-04-27 15:19 UTC, kevinhughes27 commented
Finally got this deployed! sorry for the delay. Had a couple things come up on my end.